### ISSUE TITLE
qiskit.ignis deprecated

### ISSUE THREAD

**Issue by NiklasElsaesser** [JanLahmann/Fun-with-Quantum#21]
Qiskit Ignis is deprecated and has been superseded by the [Qiskit Experiments](https://github.com/Qiskit/qiskit-experiments) project. Therefore [GHZ-on-Real-Devices.ipynb](https://github.com/JanLahmann/Fun-with-Quantum/blob/master/GHZ-on-Real-Devices.ipynb) ist not working anymore, a fix has not been found yet.

**Comment by Petzys** [comment]
Hi, thanks for your contribution. We recently updated the Qiskit version to 0.38 and every notebook should work now. 
Does the issue still exist? If so, could you give a more detailed explanation where and how to reproduce this issue?
Thanks!

**Comment by NiklasElsaesser** [comment]
thank you for the fix.
